name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change if using a different branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install Dependencies
        run: npm install  # Modify if using Yarn or pnpm

      - name: Build React App
        run: npm run build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build  # Ensure this matches your React build output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
